name: Desplegar Microservicio 1 a AWS EC2

on:
  push:
    branches:
      - main # Se ejecuta cuando subes código a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectarse por SSH y Desplegar
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Cargar entorno
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # 2. Actualizar código
            rm -rf microservicio-1
            git clone https://github.com/${{ github.repository }}.git microservicio-1
            cd microservicio-1
            npm install
            
            # 3. Configurar Red (Limpiando reglas viejas primero)
            sudo pkill -f http.server || true
            sudo pkill -f node || true
            sudo iptables -t nat -F
            sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 3000
            
            # 4. EL LANZAMIENTO DESVINCULADO
            # Usamos paréntesis para crear un subproceso y cortamos toda entrada/salida
            (nohup node index.js > app.log 2>&1 < /dev/null &)
            
            # 5. Esperar y salir
            echo "Esperando a que Node arranque..."
            sleep 5
            echo "Despliegue completado con éxito. Cerrando SSH."
            exit 0