name: Desplegar Microservicio 1 a AWS EC2

on:
  push:
    branches:
      - main # Se ejecuta cuando subes código a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectarse por SSH y Desplegar
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Instalar dependencias básicas
            sudo yum update -y
            sudo yum install -y git
            
            # 2. Instalar NVM y Node.js 16
            curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.5/install.sh | bash
            
            # Cargar NVM en la sesión actual
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # Instalar y usar Node 16
            nvm install 16
            nvm use 16
            
            # 3. Clonar o actualizar el repositorio
            rm -rf microservicio-1
            git clone https://github.com/${{ github.repository }}.git microservicio-1
            cd microservicio-1
            
            # 4. Instalar dependencias y levantar el servidor
            npm install
            
            # --- SOLUCIÓN DEL PUERTO 80 ---
            # Matamos el servidor de prueba de Python que hicimos con Terraform
            sudo pkill -f http.server || true
            # Le damos permiso a Node.js para usar el puerto 80 en esta máquina
            sudo setcap cap_net_bind_service=+ep $(which node)
            # ------------------------------
            
            # Usamos pm2 para que Node se quede corriendo en segundo plano
            npm install -g pm2
            pm2 stop ms1 || true
            pm2 start index.js --name ms1