name: Desplegar Microservicio 1 a AWS EC2

on:
  push:
    branches:
      - main # Se ejecuta cuando subes código a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectarse por SSH y Desplegar
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Cargar NVM y Node.js
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # 2. Descargar la última versión de tu código
            rm -rf microservicio-1
            git clone https://github.com/${{ github.repository }}.git microservicio-1
            cd microservicio-1
            
            # 3. Instalar dependencias
            npm install
            
            # --- TRUCO DE RED (FIREWALL) ---
            # Matamos el servidor de Python por si acaso
            sudo pkill -f http.server || true
            # Redirigimos el tráfico del puerto 80 al 3000
            sudo iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-port 3000
            # -------------------------------
            
            # 4. Arrancar la aplicación en el puerto 3000
            npm install -g pm2
            pm2 stop ms1 || true
            pm2 start index.js --name ms1