name: Desplegar Microservicio 1 a AWS EC2

on:
  push:
    branches:
      - main # Se ejecuta cuando subes c칩digo a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Conectarse por SSH y Desplegar
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # 1. Cargar el entorno de Node
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # 2. Matar a Python y cualquier app anterior para liberar el puerto
            sudo pkill -f http.server || true
            sudo pkill -f node || true
            
            # 3. Bajar tu c칩digo fresco
            rm -rf microservicio-1
            git clone https://github.com/${{ github.repository }}.git microservicio-1
            cd microservicio-1
            
            # 4. Asegurar que index.js apunte al puerto 80 autom치ticamente
            sed -i 's/const port = 3000;/const port = 80;/g' index.js
            
            # 5. Instalar dependencias y PM2
            npm install
            npm install -g pm2
            
            # 6. EL TRUCO MAESTRO: Correr PM2 como Superusuario (Root) 
            # Le pasamos el PATH para que Root sepa d칩nde encontrar Node
            sudo env PATH=$PATH $(which pm2) start index.js --name ms1
            
            exit 0